name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -f

      - name: Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key
          ssh -o StrictHostKeyChecking=no -i deploy_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} 'rsync -avz --delete ./ /home/ubuntu/'

